= MultiIssuerJWTTokenAuthenticator Configuration
:toc:
:toclevels: 3
:toc-title: Table of Contents
:sectnums:

link:../specification.adoc[Back to Main Specification]

== Configuration Properties
_See Requirement link:../requirements.adoc#NIFI-AUTH-7[NIFI-AUTH-7: Configuration Requirements]_

=== Static Properties
_See Requirement link:../requirements.adoc#NIFI-AUTH-5.3[NIFI-AUTH-5.3: Advanced Properties]_

The following properties are configured as advanced properties and are only shown when the user clicks the "Advanced" button in the processor configuration dialog.

[cols="2,1,1,2"]
|===
|Property |Type |Default |Description

|Token Header Name
|String
|Authorization
|Name of the header containing the JWT token

|JWKS Refresh Interval
|Time Period
|15 minutes
|How often to refresh the JWKS cache

|Require Valid Token
|Boolean
|true
|When true, only valid tokens result in success relationship
|===

==== Implementation of Advanced Properties
_See Requirement link:../requirements.adoc#NIFI-AUTH-5.3[NIFI-AUTH-5.3: Advanced Properties]_

The advanced properties are implemented using the `displayName` property with a special prefix to indicate they should be displayed in the advanced tab:

[source,java]
----
public static final PropertyDescriptor TOKEN_HEADER = new PropertyDescriptor.Builder()
    .name("Token Header Name")
    .displayName("Token Header Name")
    .description(i18nResolver.getTranslatedString("property.token.header.description"))
    .required(true)
    .defaultValue("Authorization")
    .addValidator(StandardValidators.NON_EMPTY_VALIDATOR)
    .expressionLanguageSupported(ExpressionLanguageScope.NONE)
    .build();

public static final PropertyDescriptor JWKS_REFRESH_INTERVAL = new PropertyDescriptor.Builder()
    .name("JWKS Refresh Interval")
    .displayName("JWKS Refresh Interval")
    .description(i18nResolver.getTranslatedString("property.jwks.refresh.description"))
    .required(true)
    .defaultValue("15 min")
    .addValidator(StandardValidators.TIME_PERIOD_VALIDATOR)
    .expressionLanguageSupported(ExpressionLanguageScope.NONE)
    .build();

public static final PropertyDescriptor REQUIRE_VALID_TOKEN = new PropertyDescriptor.Builder()
    .name("Require Valid Token")
    .displayName("Require Valid Token")
    .description(i18nResolver.getTranslatedString("property.require.valid.token.description"))
    .required(true)
    .defaultValue("true")
    .allowableValues("true", "false")
    .addValidator(StandardValidators.BOOLEAN_VALIDATOR)
    .expressionLanguageSupported(ExpressionLanguageScope.NONE)
    .build();

@Override
protected List<PropertyDescriptor> getSupportedPropertyDescriptors() {
    final List<PropertyDescriptor> properties = new ArrayList<>();
    properties.add(TOKEN_HEADER);
    properties.add(JWKS_REFRESH_INTERVAL);
    properties.add(REQUIRE_VALID_TOKEN);
    return properties;
}

@Override
protected PropertyDescriptor getSupportedDynamicPropertyDescriptor(final String propertyDescriptorName) {
    return new PropertyDescriptor.Builder()
        .name(propertyDescriptorName)
        .displayName(propertyDescriptorName)
        .description(i18nResolver.getTranslatedString("property.issuer.description"))
        .required(false)
        .dynamic(true)
        .addValidator(StandardValidators.NON_EMPTY_VALIDATOR)
        .expressionLanguageSupported(ExpressionLanguageScope.NONE)
        .build();
}

@Override
public boolean isAdvanced(PropertyDescriptor property) {
    return TOKEN_HEADER.equals(property) || 
           JWKS_REFRESH_INTERVAL.equals(property) || 
           REQUIRE_VALID_TOKEN.equals(property);
}
----

=== Dynamic Properties
_See Requirement link:../requirements.adoc#NIFI-AUTH-5.2[NIFI-AUTH-5.2: Dynamic Properties]_

Dynamic properties are used to configure token issuers. Each property represents a single issuer configuration.

[cols="2,1,1,2"]
|===
|Property |Type |Default |Description

|Issuer Identifier
|String
|N/A
|Value can be either a JWKS URL or a PEM-encoded public key
|===

== UI Configuration
_See Requirement link:../requirements.adoc#NIFI-AUTH-7.1[NIFI-AUTH-7.1: UI Configuration]_

=== Internationalized Property Descriptors
_See Requirement link:../requirements.adoc#NIFI-AUTH-17[NIFI-AUTH-17: Internationalization Support]_

The processor uses internationalized strings for all UI elements:

[source,java]
----
// Load resource bundle
private static final ResourceBundle MESSAGES = ResourceBundle.getBundle(
    "de.cuioss.nifi.processors.auth.messages.Messages",
    Locale.getDefault());

public static final PropertyDescriptor TOKEN_HEADER = new PropertyDescriptor.Builder()
    .name("Token Header Name")
    .displayName(MESSAGES.getString("property.token.header.name"))
    .description(MESSAGES.getString("property.token.header.description"))
    .required(true)
    .defaultValue("Authorization")
    .addValidator(StandardValidators.NON_EMPTY_VALIDATOR)
    .build();

public static final PropertyDescriptor JWKS_REFRESH_INTERVAL = new PropertyDescriptor.Builder()
    .name("JWKS Refresh Interval")
    .displayName(MESSAGES.getString("property.jwks.refresh.interval.name"))
    .description(MESSAGES.getString("property.jwks.refresh.interval.description"))
    .required(true)
    .defaultValue("15 min")
    .addValidator(StandardValidators.TIME_PERIOD_VALIDATOR)
    .build();

public static final PropertyDescriptor REQUIRE_VALID_TOKEN = new PropertyDescriptor.Builder()
    .name("Require Valid Token")
    .displayName(MESSAGES.getString("property.require.valid.token.name"))
    .description(MESSAGES.getString("property.require.valid.token.description"))
    .required(true)
    .defaultValue("true")
    .allowableValues("true", "false")
    .build();

@Override
protected List<PropertyDescriptor> getSupportedPropertyDescriptors() {
    final List<PropertyDescriptor> properties = new ArrayList<>();
    properties.add(TOKEN_HEADER);
    properties.add(JWKS_REFRESH_INTERVAL);
    properties.add(REQUIRE_VALID_TOKEN);
    return properties;
}

@Override
protected PropertyDescriptor getSupportedDynamicPropertyDescriptor(final String propertyDescriptorName) {
    return new PropertyDescriptor.Builder()
        .name(propertyDescriptorName)
        .displayName("Issuer Configuration: " + propertyDescriptorName)
        .description("Configuration for issuer: " + propertyDescriptorName + 
                     ". Value can be either a JWKS URL or a PEM-encoded public key.")
        .required(true)
        .dynamic(true)
        .addValidator(StandardValidators.NON_EMPTY_VALIDATOR)
        .build();
}
----

=== Custom UI Components

==== JWKS Endpoint Test Button
_See Requirement link:../requirements.adoc#NIFI-AUTH-7.1[NIFI-AUTH-7.1: UI Configuration]_

The JWKS Endpoint Test Button allows users to validate that a JWKS endpoint is accessible and returns valid JWKS data.

[source,javascript]
----
// UI Extension for JWKS Test Button
define(['jquery'], function ($) {
    return {
        /**
         * Initialize the custom UI.
         */
        init: function (element, propertyValue, callback) {
            // Load i18n resources
            var i18n = {
                en: {
                    testConnection: "Test Connection",
                    connectionSuccessful: "Connection successful",
                    connectionFailed: "Connection failed: ",
                    testFailed: "Test failed: ",
                    notValidUrl: "Not a valid URL"
                },
                de: {
                    testConnection: "Verbindung testen",
                    connectionSuccessful: "Verbindung erfolgreich",
                    connectionFailed: "Verbindung fehlgeschlagen: ",
                    testFailed: "Test fehlgeschlagen: ",
                    notValidUrl: "Keine gültige URL"
                }
            };
            
            // Determine language based on browser locale
            var lang = (navigator.language || navigator.userLanguage).substring(0, 2);
            var texts = i18n[lang] || i18n.en; // Default to English if language not supported
            
            // Create UI elements
            var container = $('<div class="jwks-verification-container"></div>');
            var verifyButton = $('<button type="button" class="verify-jwks-button">' + texts.testConnection + '</button>');
            var resultContainer = $('<div class="verification-result"></div>');
            
            // Add elements to the DOM
            container.append(verifyButton).append(resultContainer);
            $(element).append(container);
            
            // Handle button click
            verifyButton.on('click', function () {
                var jwksUrl = propertyValue;
                if (jwksUrl && jwksUrl.startsWith('http')) {
                    resultContainer.html('<span class="fa fa-spinner fa-spin"></span>');
                    
                    // Make AJAX request to verify JWKS URL
                    $.ajax({
                        type: 'POST',
                        url: '../nifi-api/processors/verify-jwks',
                        data: JSON.stringify({
                            jwksUrl: jwksUrl
                        }),
                        contentType: 'application/json',
                        dataType: 'json'
                    }).done(function (response) {
                        if (response.valid) {
                            resultContainer.html('<span class="fa fa-check" style="color: green;"></span> ' + 
                                                texts.connectionSuccessful);
                        } else {
                            resultContainer.html('<span class="fa fa-times" style="color: red;"></span> ' + 
                                                texts.connectionFailed + response.explanation);
                        }
                    }).fail(function (xhr) {
                        resultContainer.html('<span class="fa fa-times" style="color: red;"></span> ' + 
                                            texts.testFailed + xhr.responseText);
                    });
                } else {
                    resultContainer.html('<span class="fa fa-times" style="color: red;"></span> ' + 
                                        texts.notValidUrl);
                }
            });
            
            callback({
                validate: function () {
                    return true;
                },
                getValue: function () {
                    return propertyValue;
                },
                setValue: function (newValue) {
                    propertyValue = newValue;
                }
            });
        },
        
        /**
         * Clean up any resources before the element is removed from the DOM.
         */
        cleanup: function (element) {
            $(element).find('.verify-jwks-button').off();
        }
    };
}
----

==== Token Verification Interface
_See Requirement link:../requirements.adoc#NIFI-AUTH-7.3[NIFI-AUTH-7.3: Verification]_

The Token Verification Interface allows users to test JWT tokens against the current processor configuration.

[source,javascript]
----
define(['jquery'], function ($) {
    return {
        /**
         * Initialize the custom UI.
         */
        init: function (element, processorId, callback) {
            // Load i18n resources
            var i18n = {
                en: {
                    tokenPlaceholder: "Paste JWT token here...",
                    verifyButton: "Verify Token",
                    enterToken: "Please enter a JWT token.",
                    verifyingToken: "Verifying token...",
                    tokenValid: "Token is valid!",
                    tokenDetails: "Token Details:",
                    issuer: "Issuer:",
                    subject: "Subject:",
                    expires: "Expires:",
                    claims: "Claims:",
                    flowFileAttributes: "FlowFile Attributes:",
                    tokenInvalid: "Token validation failed!",
                    errorDetails: "Error Details:",
                    suggestion: "Suggestion:",
                    verificationFailed: "Verification request failed: "
                },
                de: {
                    tokenPlaceholder: "JWT-Token hier einfügen...",
                    verifyButton: "Token überprüfen",
                    enterToken: "Bitte geben Sie ein JWT-Token ein.",
                    verifyingToken: "Token wird überprüft...",
                    tokenValid: "Token ist gültig!",
                    tokenDetails: "Token-Details:",
                    issuer: "Aussteller:",
                    subject: "Betreff:",
                    expires: "Läuft ab:",
                    claims: "Claims:",
                    flowFileAttributes: "FlowFile-Attribute:",
                    tokenInvalid: "Token-Validierung fehlgeschlagen!",
                    errorDetails: "Fehlerdetails:",
                    suggestion: "Vorschlag:",
                    verificationFailed: "Überprüfungsanfrage fehlgeschlagen: "
                }
            };
            
            // Determine language based on browser locale
            var lang = (navigator.language || navigator.userLanguage).substring(0, 2);
            var texts = i18n[lang] || i18n.en; // Default to English if language not supported
            
            // Create UI elements
            var container = $('<div class="token-verification-container"></div>');
            var tokenInput = $('<textarea class="token-input" placeholder="' + texts.tokenPlaceholder + '"></textarea>');
            var verifyButton = $('<button type="button" class="verify-token-button">' + texts.verifyButton + '</button>');
            var resultContainer = $('<div class="verification-result"></div>');
            
            // Add elements to the DOM
            container.append(tokenInput)
                    .append(verifyButton)
                    .append(resultContainer);
            $(element).append(container);
            
            // Handle button click
            verifyButton.on('click', function () {
                var token = tokenInput.val().trim();
                if (!token) {
                    resultContainer.html('<div class="message-warning">' + texts.enterToken + '</div>');
                    return;
                }
                
                resultContainer.html('<span class="fa fa-spinner fa-spin"></span> ' + texts.verifyingToken);
                
                // Make AJAX request to verify the token
                $.ajax({
                    type: 'POST',
                    url: '../nifi-api/processors/' + processorId + '/verify-token',
                    data: JSON.stringify({
                        token: token
                    }),
                    contentType: 'application/json',
                    dataType: 'json'
                }).done(function (response) {
                    if (response.valid) {
                        // Show success message with token details
                        var html = '<div class="message-success">' + texts.tokenValid + '</div>';
                        html += '<div class="token-details">';
                        html += '<h4>' + texts.tokenDetails + '</h4>';
                        html += '<table class="token-info-table">';
                        html += '<tr><td>' + texts.issuer + '</td><td>' + response.issuer + '</td></tr>';
                        html += '<tr><td>' + texts.subject + '</td><td>' + response.subject + '</td></tr>';
                        html += '<tr><td>' + texts.expires + '</td><td>' + new Date(response.expiresAt * 1000).toLocaleString(lang) + '</td></tr>';
                        
                        // Add claims
                        html += '<tr><td colspan="2"><h4>' + texts.claims + '</h4></td></tr>';
                        for (var claim in response.claims) {
                            html += '<tr><td>' + claim + ':</td><td>' + JSON.stringify(response.claims[claim]) + '</td></tr>';
                        }
                        
                        // Add attributes that would be added
                        html += '<tr><td colspan="2"><h4>' + texts.flowFileAttributes + '</h4></td></tr>';
                        for (var attr in response.attributes) {
                            html += '<tr><td>' + attr + ':</td><td>' + response.attributes[attr] + '</td></tr>';
                        }
                        
                        html += '</table>';
                        html += '</div>';
                        resultContainer.html(html);
                    } else {
                        // Show error message
                        var html = '<div class="message-error">' + texts.tokenInvalid + '</div>';
                        html += '<div class="error-details">';
                        html += '<h4>' + texts.errorDetails + '</h4>';
                        html += '<p>' + response.reason + '</p>';
                        
                        // Add suggestion if available
                        if (response.suggestion) {
                            html += '<h4>' + texts.suggestion + '</h4>';
                            html += '<p>' + response.suggestion + '</p>';
                        }
                        
                        html += '</div>';
                        resultContainer.html(html);
                    }
                }).fail(function (xhr) {
                    resultContainer.html('<div class="message-error">' + texts.verificationFailed + 
                                         xhr.responseText + '</div>');
                });
            });
            
            callback();
        },
        
        /**
         * Clean up any resources before the element is removed from the DOM.
         */
        cleanup: function (element) {
            $(element).find('.verify-token-button').off();
        }
    };
}
----


== Configuration Examples

=== Basic Configuration
_See Requirement link:../requirements.adoc#NIFI-AUTH-7.2[NIFI-AUTH-7.2: Token Validation Configuration]_

[source,properties]
----
# Static properties
Token Header Name: Authorization
JWKS Refresh Interval: 15 min
Require Valid Token: true

# Dynamic properties (issuers)
keycloak: https://auth.example.com/realms/master/protocol/openid-connect/certs
azure: https://login.microsoftonline.com/common/discovery/keys
----

=== Multi-Issuer Configuration
_See Requirement link:../requirements.adoc#NIFI-AUTH-4[NIFI-AUTH-4: Multiple Issuer Support]_

[source,properties]
----
# Static properties
Token Header Name: Authorization
JWKS Refresh Interval: 30 min
Require Valid Token: true

# Dynamic properties (issuers)
internal-keycloak: https://auth.internal.example.com/realms/master/protocol/openid-connect/certs
customer-keycloak: https://auth.customer.example.com/realms/master/protocol/openid-connect/certs
partner-auth: https://auth.partner.example.com/.well-known/jwks.json
legacy-system: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...
----

=== Authorization Configuration
_See Requirement link:../requirements.adoc#NIFI-AUTH-7.4[NIFI-AUTH-7.4: Authorization Configuration]_

[source,properties]
----
# Static properties
Token Header Name: Authorization
JWKS Refresh Interval: 15 min
Require Valid Token: true
Required Scopes: api:read,api:write
Required Roles: admin,power-user

# Dynamic properties (issuers)
keycloak: https://auth.example.com/realms/master/protocol/openid-connect/certs
----
