/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.cuioss.nifi.ui.servlets;

import de.cuioss.tools.logging.CuiLogger;
import jakarta.servlet.*;
import jakarta.servlet.annotation.WebFilter;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.IOException;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Authentication filter for JWT API endpoints using API key-based security.
 * This filter ensures that only authorized requests can access the JWT validation
 * endpoints by validating API keys generated by processors.
 * 
 * The filter intercepts requests to /nifi-api/processors/jwt/* and validates:
 * 1. X-API-Key header is present
 * 2. X-Processor-Id header is present  
 * 3. API key matches the one generated for the processor
 * 
 * API keys are generated per processor instance and stored in memory.
 */
@WebFilter("/nifi-api/processors/jwt/*")
public class ApiKeyAuthenticationFilter implements Filter {

    private static final CuiLogger LOGGER = new CuiLogger(ApiKeyAuthenticationFilter.class);

    // API key storage: processorId -> apiKey
    private static final ConcurrentHashMap<String, String> apiKeys = new ConcurrentHashMap<>();

    // Headers
    private static final String API_KEY_HEADER = "X-API-Key";
    private static final String PROCESSOR_ID_HEADER = "X-Processor-Id";

    @Override
    public void init(FilterConfig filterConfig) throws ServletException {
        LOGGER.info("Initializing API Key Authentication Filter");
    }

    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
            throws IOException, ServletException {

        HttpServletRequest httpRequest = (HttpServletRequest) request;
        HttpServletResponse httpResponse = (HttpServletResponse) response;

        String requestPath = httpRequest.getServletPath();
        String method = httpRequest.getMethod();

        LOGGER.debug("Processing request: %s %s", method, requestPath);

        // Check if this is an E2E test endpoint (no authentication required)
        if (requestPath != null && requestPath.startsWith("/api/token/")) {
            LOGGER.debug("Skipping authentication for E2E test endpoint: %s", requestPath);
            chain.doFilter(request, response);
            return;
        }

        // Extract API key and processor ID from headers
        String apiKey = httpRequest.getHeader(API_KEY_HEADER);
        String processorId = httpRequest.getHeader(PROCESSOR_ID_HEADER);

        // Validate headers are present
        if (apiKey == null || apiKey.trim().isEmpty()) {
            LOGGER.warn("Missing API key header in request to %s", requestPath);
            sendUnauthorizedResponse(httpResponse, "Missing or empty API key header");
            return;
        }

        if (processorId == null || processorId.trim().isEmpty()) {
            LOGGER.warn("Missing processor ID header in request to %s", requestPath);
            sendUnauthorizedResponse(httpResponse, "Missing or empty processor ID header");
            return;
        }

        // Validate API key
        if (!isValidApiKey(processorId, apiKey)) {
            LOGGER.warn("Invalid API key for processor %s in request to %s", processorId, requestPath);
            sendUnauthorizedResponse(httpResponse, "Invalid or expired API key");
            return;
        }

        LOGGER.debug("API key validation successful for processor %s", processorId);

        // Continue with the request
        chain.doFilter(request, response);
    }

    @Override
    public void destroy() {
        LOGGER.info("Destroying API Key Authentication Filter");
        // Clear all API keys on shutdown
        apiKeys.clear();
    }

    /**
     * Validates an API key for a specific processor.
     * 
     * @param processorId The processor ID
     * @param apiKey The API key to validate
     * @return true if the API key is valid, false otherwise
     */
    private boolean isValidApiKey(String processorId, String apiKey) {
        String expectedKey = apiKeys.get(processorId);
        boolean isValid = expectedKey != null && expectedKey.equals(apiKey);

        if (!isValid) {
            LOGGER.debug("API key validation failed for processor %s (key exists: %s)",
                    processorId, expectedKey != null);
        }

        return isValid;
    }

    /**
     * Sends an unauthorized response in JSON format to match the API response format.
     */
    private void sendUnauthorizedResponse(HttpServletResponse response, String message)
            throws IOException {

        response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
        response.setContentType("application/json");
        response.setCharacterEncoding("UTF-8");

        // Send JSON error response that matches the servlet response format
        String jsonResponse = "{\"error\":\"%s\",\"valid\":false,\"accessible\":false}".formatted(
                escapeJsonString(message));

        try (var writer = response.getWriter()) {
            writer.write(jsonResponse);
        } catch (IOException e) {
            LOGGER.error(e, "Failed to write unauthorized response");
            throw e;
        }
    }

    /**
     * Escapes a string for safe inclusion in JSON.
     */
    private String escapeJsonString(String str) {
        if (str == null) return "";
        return str.replace("\"", "\\\"")
                .replace("\\", "\\\\")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t");
    }

    // Static methods for managing API keys
    
    /**
     * Generates a unique API key for a processor instance.
     * The API key is a cryptographically secure random string.
     * 
     * @param processorId The processor ID
     * @return The generated API key
     */
    public static String generateApiKeyForProcessor(String processorId) {
        if (processorId == null || processorId.trim().isEmpty()) {
            throw new IllegalArgumentException("Processor ID cannot be null or empty");
        }

        // Generate 32 bytes of secure random data
        SecureRandom random = new SecureRandom();
        byte[] bytes = new byte[32];
        random.nextBytes(bytes);

        // Encode as URL-safe base64 without padding
        String apiKey = Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);

        // Store the API key
        apiKeys.put(processorId, apiKey);

        LOGGER.info("Generated API key for processor %s", processorId);
        return apiKey;
    }

    /**
     * Revokes the API key for a processor.
     * This is called when a processor is stopped or removed.
     * 
     * @param processorId The processor ID
     * @return true if an API key was removed, false if none existed
     */
    public static boolean revokeApiKeyForProcessor(String processorId) {
        if (processorId == null || processorId.trim().isEmpty()) {
            return false;
        }

        boolean removed = apiKeys.remove(processorId) != null;
        if (removed) {
            LOGGER.info("Revoked API key for processor %s", processorId);
        } else {
            LOGGER.debug("No API key found to revoke for processor %s", processorId);
        }

        return removed;
    }

    /**
     * Gets the current API key for a processor.
     * This is mainly for testing purposes.
     * 
     * @param processorId The processor ID
     * @return The API key, or null if none exists
     */
    public static String getApiKeyForProcessor(String processorId) {
        return apiKeys.get(processorId);
    }

    /**
     * Checks if an API key exists for a processor.
     * 
     * @param processorId The processor ID
     * @return true if an API key exists, false otherwise
     */
    public static boolean hasApiKeyForProcessor(String processorId) {
        return apiKeys.containsKey(processorId);
    }

    /**
     * Clears all API keys.
     * This is mainly for testing purposes.
     */
    public static void clearAllApiKeys() {
        int count = apiKeys.size();
        apiKeys.clear();
        LOGGER.info("Cleared %d API keys", count);
    }

    /**
     * Gets the number of active API keys.
     * This is mainly for monitoring purposes.
     * 
     * @return The number of active API keys
     */
    public static int getActiveApiKeyCount() {
        return apiKeys.size();
    }
}