@startuml service-to-service-authentication
!pragma layout smetana
skinparam componentStyle rectangle

component "Service A" as serviceA
component "JWT Token\nAuthenticator" as authenticator
component "Service B" as serviceB
component "Token\nIssuer" as tokenIssuer
component "Identity\nProvider" as idp

serviceA --> authenticator
authenticator --> serviceB
serviceA --> tokenIssuer
authenticator --> idp

@enduml